### ISSUE TITLE
starter project doesn't get loaded 

### ISSUE THREAD

**Issue by tsdeepak** [optimajet/HRM#1]
cloned the HRM repo -> opened in VS2017 -> opened the solution -> OptimaJet.DWKit.StarterApplication.csproj doesn't load 

error --> Project file is incomplete. Expected imports are missing.

![image](https://user-images.githubusercontent.com/375801/49449747-9566d400-f801-11e8-9421-2f7e186af7e5.png)

**Comment by optimajet** [comment]
Have you installed the lasted version of .NET Core?

Also, look into [https://stackoverflow.com/questions/49432666/project-file-is-incomplete-expected-imports-are-missing](the article)
